# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Generate Cypress Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name:    Run Cypress Tests
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install cypress and verify
      run :  |
            npm ci
            $(npm bin)/cypress verify
            
    - name: Run Cypress Tests
      run : npx cypress run
      continue-on-error: false
      
      
    - name: Deploy Report to page
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
